dbt_demo:
  target: dev
  outputs:
    dev:
      dbname: bootcamp_db
      host: localhost
      pass: password
      port: 5432
      schema: public
      threads: 5
      type: postgres
      user: user
